/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as RefundAndCancellationPolicyRouteImport } from './routes/refund-and-cancellation-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AbouUsRouteImport } from './routes/abou-us'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as PresentationIdRouteImport } from './routes/presentation/$id'
import { Route as PresentIdRouteImport } from './routes/present/$id'
import { Route as OutlineDraftIdRouteImport } from './routes/outline/$draftId'
import { Route as ApiMetricsRouteImport } from './routes/api/metrics'
import { Route as ApiDbHealthRouteImport } from './routes/api/db-health'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ApiPresentationsIndexRouteImport } from './routes/api/presentations/index'
import { Route as ApiBrandKitsIndexRouteImport } from './routes/api/brand-kits/index'
import { Route as ApiWebhooksPaddleRouteImport } from './routes/api/webhooks/paddle'
import { Route as ApiShareTokenRouteImport } from './routes/api/share/$token'
import { Route as ApiPresentationsOutlineRouteImport } from './routes/api/presentations/outline'
import { Route as ApiPresentationsImportRouteImport } from './routes/api/presentations/import'
import { Route as ApiPresentationsHistoryRouteImport } from './routes/api/presentations/history'
import { Route as ApiPaymentVerifyRouteImport } from './routes/api/payment/verify'
import { Route as ApiPaymentCreateOrderRouteImport } from './routes/api/payment/create-order'
import { Route as ApiHealthSystemRouteImport } from './routes/api/health/system'
import { Route as ApiBrandKitsKitIdRouteImport } from './routes/api/brand-kits/$kitId'
import { Route as ApiBillingPortalRouteImport } from './routes/api/billing/portal'
import { Route as ApiBillingMeRouteImport } from './routes/api/billing/me'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAnalyticsSummaryRouteImport } from './routes/api/analytics/summary'
import { Route as ApiPresentationsIdIndexRouteImport } from './routes/api/presentations/$id/index'
import { Route as ApiHealthWorkersIndexRouteImport } from './routes/api/health/workers/index'
import { Route as ApiDraftsDraftIdIndexRouteImport } from './routes/api/drafts/$draftId/index'
import { Route as ApiPresentationsIdTextActionsRouteImport } from './routes/api/presentations/$id/text-actions'
import { Route as ApiPresentationsIdTemplateRouteImport } from './routes/api/presentations/$id/template'
import { Route as ApiPresentationsIdShareRouteImport } from './routes/api/presentations/$id/share'
import { Route as ApiPresentationsIdMembersRouteImport } from './routes/api/presentations/$id/members'
import { Route as ApiPresentationsIdExportRouteImport } from './routes/api/presentations/$id/export'
import { Route as ApiPresentationsIdEventsRouteImport } from './routes/api/presentations/$id/events'
import { Route as ApiPresentationsIdCitationModeRouteImport } from './routes/api/presentations/$id/citation-mode'
import { Route as ApiPresentationsIdBrandKitRouteImport } from './routes/api/presentations/$id/brand-kit'
import { Route as ApiHealthWorkersWorkerClassRouteImport } from './routes/api/health/workers/$workerClass'
import { Route as ApiDraftsDraftIdRegenerateRouteImport } from './routes/api/drafts/$draftId/regenerate'
import { Route as ApiDraftsDraftIdGenerateRouteImport } from './routes/api/drafts/$draftId/generate'
import { Route as ApiDraftsDraftIdEventsRouteImport } from './routes/api/drafts/$draftId/events'
import { Route as ApiPresentationsIdVersionsIndexRouteImport } from './routes/api/presentations/$id/versions/index'
import { Route as ApiPresentationsIdSlidesIndexRouteImport } from './routes/api/presentations/$id/slides/index'
import { Route as ApiDraftsDraftIdSlidesIndexRouteImport } from './routes/api/drafts/$draftId/slides/index'
import { Route as ApiPresentationsIdSlidesReorderRouteImport } from './routes/api/presentations/$id/slides/reorder'
import { Route as ApiDraftsDraftIdSlidesSlideIdRouteImport } from './routes/api/drafts/$draftId/slides/$slideId'
import { Route as ApiPresentationsIdSlidesSlideIdIndexRouteImport } from './routes/api/presentations/$id/slides/$slideId/index'
import { Route as ApiPresentationsIdVersionsVersionIdRestoreRouteImport } from './routes/api/presentations/$id/versions/$versionId/restore'
import { Route as ApiPresentationsIdSlidesSlideIdVisualizeRouteImport } from './routes/api/presentations/$id/slides/$slideId/visualize'
import { Route as ApiPresentationsIdSlidesSlideIdRegenerateRouteImport } from './routes/api/presentations/$id/slides/$slideId/regenerate'
import { Route as ApiPresentationsIdSlidesSlideIdImageUploadRouteImport } from './routes/api/presentations/$id/slides/$slideId/image-upload'
import { Route as ApiPresentationsIdSlidesSlideIdImageRegenerateRouteImport } from './routes/api/presentations/$id/slides/$slideId/image-regenerate'
import { Route as ApiPresentationsIdSlidesSlideIdDuplicateRouteImport } from './routes/api/presentations/$id/slides/$slideId/duplicate'
import { Route as ApiPresentationsIdSlidesSlideIdChatRouteImport } from './routes/api/presentations/$id/slides/$slideId/chat'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundAndCancellationPolicyRoute =
  RefundAndCancellationPolicyRouteImport.update({
    id: '/refund-and-cancellation-policy',
    path: '/refund-and-cancellation-policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AbouUsRoute = AbouUsRouteImport.update({
  id: '/abou-us',
  path: '/abou-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationIdRoute = PresentationIdRouteImport.update({
  id: '/presentation/$id',
  path: '/presentation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentIdRoute = PresentIdRouteImport.update({
  id: '/present/$id',
  path: '/present/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OutlineDraftIdRoute = OutlineDraftIdRouteImport.update({
  id: '/outline/$draftId',
  path: '/outline/$draftId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetricsRoute = ApiMetricsRouteImport.update({
  id: '/api/metrics',
  path: '/api/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbHealthRoute = ApiDbHealthRouteImport.update({
  id: '/api/db-health',
  path: '/api/db-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiPresentationsIndexRoute = ApiPresentationsIndexRouteImport.update({
  id: '/api/presentations/',
  path: '/api/presentations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandKitsIndexRoute = ApiBrandKitsIndexRouteImport.update({
  id: '/api/brand-kits/',
  path: '/api/brand-kits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaddleRoute = ApiWebhooksPaddleRouteImport.update({
  id: '/api/webhooks/paddle',
  path: '/api/webhooks/paddle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareTokenRoute = ApiShareTokenRouteImport.update({
  id: '/api/share/$token',
  path: '/api/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPresentationsOutlineRoute = ApiPresentationsOutlineRouteImport.update({
  id: '/api/presentations/outline',
  path: '/api/presentations/outline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPresentationsImportRoute = ApiPresentationsImportRouteImport.update({
  id: '/api/presentations/import',
  path: '/api/presentations/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPresentationsHistoryRoute = ApiPresentationsHistoryRouteImport.update({
  id: '/api/presentations/history',
  path: '/api/presentations/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentVerifyRoute = ApiPaymentVerifyRouteImport.update({
  id: '/api/payment/verify',
  path: '/api/payment/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCreateOrderRoute = ApiPaymentCreateOrderRouteImport.update({
  id: '/api/payment/create-order',
  path: '/api/payment/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthSystemRoute = ApiHealthSystemRouteImport.update({
  id: '/api/health/system',
  path: '/api/health/system',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandKitsKitIdRoute = ApiBrandKitsKitIdRouteImport.update({
  id: '/api/brand-kits/$kitId',
  path: '/api/brand-kits/$kitId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing/portal',
  path: '/api/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingMeRoute = ApiBillingMeRouteImport.update({
  id: '/api/billing/me',
  path: '/api/billing/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsSummaryRoute = ApiAnalyticsSummaryRouteImport.update({
  id: '/api/analytics/summary',
  path: '/api/analytics/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPresentationsIdIndexRoute = ApiPresentationsIdIndexRouteImport.update({
  id: '/api/presentations/$id/',
  path: '/api/presentations/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthWorkersIndexRoute = ApiHealthWorkersIndexRouteImport.update({
  id: '/api/health/workers/',
  path: '/api/health/workers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftsDraftIdIndexRoute = ApiDraftsDraftIdIndexRouteImport.update({
  id: '/api/drafts/$draftId/',
  path: '/api/drafts/$draftId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPresentationsIdTextActionsRoute =
  ApiPresentationsIdTextActionsRouteImport.update({
    id: '/api/presentations/$id/text-actions',
    path: '/api/presentations/$id/text-actions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPresentationsIdTemplateRoute =
  ApiPresentationsIdTemplateRouteImport.update({
    id: '/api/presentations/$id/template',
    path: '/api/presentations/$id/template',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPresentationsIdShareRoute = ApiPresentationsIdShareRouteImport.update({
  id: '/api/presentations/$id/share',
  path: '/api/presentations/$id/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPresentationsIdMembersRoute =
  ApiPresentationsIdMembersRouteImport.update({
    id: '/api/presentations/$id/members',
    path: '/api/presentations/$id/members',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPresentationsIdExportRoute =
  ApiPresentationsIdExportRouteImport.update({
    id: '/api/presentations/$id/export',
    path: '/api/presentations/$id/export',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPresentationsIdEventsRoute =
  ApiPresentationsIdEventsRouteImport.update({
    id: '/api/presentations/$id/events',
    path: '/api/presentations/$id/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPresentationsIdCitationModeRoute =
  ApiPresentationsIdCitationModeRouteImport.update({
    id: '/api/presentations/$id/citation-mode',
    path: '/api/presentations/$id/citation-mode',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPresentationsIdBrandKitRoute =
  ApiPresentationsIdBrandKitRouteImport.update({
    id: '/api/presentations/$id/brand-kit',
    path: '/api/presentations/$id/brand-kit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHealthWorkersWorkerClassRoute =
  ApiHealthWorkersWorkerClassRouteImport.update({
    id: '/api/health/workers/$workerClass',
    path: '/api/health/workers/$workerClass',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDraftsDraftIdRegenerateRoute =
  ApiDraftsDraftIdRegenerateRouteImport.update({
    id: '/api/drafts/$draftId/regenerate',
    path: '/api/drafts/$draftId/regenerate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDraftsDraftIdGenerateRoute =
  ApiDraftsDraftIdGenerateRouteImport.update({
    id: '/api/drafts/$draftId/generate',
    path: '/api/drafts/$draftId/generate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDraftsDraftIdEventsRoute = ApiDraftsDraftIdEventsRouteImport.update({
  id: '/api/drafts/$draftId/events',
  path: '/api/drafts/$draftId/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPresentationsIdVersionsIndexRoute =
  ApiPresentationsIdVersionsIndexRouteImport.update({
    id: '/api/presentations/$id/versions/',
    path: '/api/presentations/$id/versions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPresentationsIdSlidesIndexRoute =
  ApiPresentationsIdSlidesIndexRouteImport.update({
    id: '/api/presentations/$id/slides/',
    path: '/api/presentations/$id/slides/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDraftsDraftIdSlidesIndexRoute =
  ApiDraftsDraftIdSlidesIndexRouteImport.update({
    id: '/api/drafts/$draftId/slides/',
    path: '/api/drafts/$draftId/slides/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPresentationsIdSlidesReorderRoute =
  ApiPresentationsIdSlidesReorderRouteImport.update({
    id: '/api/presentations/$id/slides/reorder',
    path: '/api/presentations/$id/slides/reorder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDraftsDraftIdSlidesSlideIdRoute =
  ApiDraftsDraftIdSlidesSlideIdRouteImport.update({
    id: '/api/drafts/$draftId/slides/$slideId',
    path: '/api/drafts/$draftId/slides/$slideId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPresentationsIdSlidesSlideIdIndexRoute =
  ApiPresentationsIdSlidesSlideIdIndexRouteImport.update({
    id: '/api/presentations/$id/slides/$slideId/',
    path: '/api/presentations/$id/slides/$slideId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPresentationsIdVersionsVersionIdRestoreRoute =
  ApiPresentationsIdVersionsVersionIdRestoreRouteImport.update({
    id: '/api/presentations/$id/versions/$versionId/restore',
    path: '/api/presentations/$id/versions/$versionId/restore',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPresentationsIdSlidesSlideIdVisualizeRoute =
  ApiPresentationsIdSlidesSlideIdVisualizeRouteImport.update({
    id: '/api/presentations/$id/slides/$slideId/visualize',
    path: '/api/presentations/$id/slides/$slideId/visualize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPresentationsIdSlidesSlideIdRegenerateRoute =
  ApiPresentationsIdSlidesSlideIdRegenerateRouteImport.update({
    id: '/api/presentations/$id/slides/$slideId/regenerate',
    path: '/api/presentations/$id/slides/$slideId/regenerate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPresentationsIdSlidesSlideIdImageUploadRoute =
  ApiPresentationsIdSlidesSlideIdImageUploadRouteImport.update({
    id: '/api/presentations/$id/slides/$slideId/image-upload',
    path: '/api/presentations/$id/slides/$slideId/image-upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPresentationsIdSlidesSlideIdImageRegenerateRoute =
  ApiPresentationsIdSlidesSlideIdImageRegenerateRouteImport.update({
    id: '/api/presentations/$id/slides/$slideId/image-regenerate',
    path: '/api/presentations/$id/slides/$slideId/image-regenerate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPresentationsIdSlidesSlideIdDuplicateRoute =
  ApiPresentationsIdSlidesSlideIdDuplicateRouteImport.update({
    id: '/api/presentations/$id/slides/$slideId/duplicate',
    path: '/api/presentations/$id/slides/$slideId/duplicate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPresentationsIdSlidesSlideIdChatRoute =
  ApiPresentationsIdSlidesSlideIdChatRouteImport.update({
    id: '/api/presentations/$id/slides/$slideId/chat',
    path: '/api/presentations/$id/slides/$slideId/chat',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abou-us': typeof AbouUsRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/analytics': typeof AnalyticsRoute
  '/contact-us': typeof ContactUsRoute
  '/home': typeof HomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-and-cancellation-policy': typeof RefundAndCancellationPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/login': typeof AuthLoginRoute
  '/api/db-health': typeof ApiDbHealthRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/outline/$draftId': typeof OutlineDraftIdRoute
  '/present/$id': typeof PresentIdRoute
  '/presentation/$id': typeof PresentationIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/api/analytics/summary': typeof ApiAnalyticsSummaryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/me': typeof ApiBillingMeRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/brand-kits/$kitId': typeof ApiBrandKitsKitIdRoute
  '/api/health/system': typeof ApiHealthSystemRoute
  '/api/payment/create-order': typeof ApiPaymentCreateOrderRoute
  '/api/payment/verify': typeof ApiPaymentVerifyRoute
  '/api/presentations/history': typeof ApiPresentationsHistoryRoute
  '/api/presentations/import': typeof ApiPresentationsImportRoute
  '/api/presentations/outline': typeof ApiPresentationsOutlineRoute
  '/api/share/$token': typeof ApiShareTokenRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
  '/api/brand-kits/': typeof ApiBrandKitsIndexRoute
  '/api/presentations/': typeof ApiPresentationsIndexRoute
  '/api/drafts/$draftId/events': typeof ApiDraftsDraftIdEventsRoute
  '/api/drafts/$draftId/generate': typeof ApiDraftsDraftIdGenerateRoute
  '/api/drafts/$draftId/regenerate': typeof ApiDraftsDraftIdRegenerateRoute
  '/api/health/workers/$workerClass': typeof ApiHealthWorkersWorkerClassRoute
  '/api/presentations/$id/brand-kit': typeof ApiPresentationsIdBrandKitRoute
  '/api/presentations/$id/citation-mode': typeof ApiPresentationsIdCitationModeRoute
  '/api/presentations/$id/events': typeof ApiPresentationsIdEventsRoute
  '/api/presentations/$id/export': typeof ApiPresentationsIdExportRoute
  '/api/presentations/$id/members': typeof ApiPresentationsIdMembersRoute
  '/api/presentations/$id/share': typeof ApiPresentationsIdShareRoute
  '/api/presentations/$id/template': typeof ApiPresentationsIdTemplateRoute
  '/api/presentations/$id/text-actions': typeof ApiPresentationsIdTextActionsRoute
  '/api/drafts/$draftId/': typeof ApiDraftsDraftIdIndexRoute
  '/api/health/workers/': typeof ApiHealthWorkersIndexRoute
  '/api/presentations/$id/': typeof ApiPresentationsIdIndexRoute
  '/api/drafts/$draftId/slides/$slideId': typeof ApiDraftsDraftIdSlidesSlideIdRoute
  '/api/presentations/$id/slides/reorder': typeof ApiPresentationsIdSlidesReorderRoute
  '/api/drafts/$draftId/slides/': typeof ApiDraftsDraftIdSlidesIndexRoute
  '/api/presentations/$id/slides/': typeof ApiPresentationsIdSlidesIndexRoute
  '/api/presentations/$id/versions/': typeof ApiPresentationsIdVersionsIndexRoute
  '/api/presentations/$id/slides/$slideId/chat': typeof ApiPresentationsIdSlidesSlideIdChatRoute
  '/api/presentations/$id/slides/$slideId/duplicate': typeof ApiPresentationsIdSlidesSlideIdDuplicateRoute
  '/api/presentations/$id/slides/$slideId/image-regenerate': typeof ApiPresentationsIdSlidesSlideIdImageRegenerateRoute
  '/api/presentations/$id/slides/$slideId/image-upload': typeof ApiPresentationsIdSlidesSlideIdImageUploadRoute
  '/api/presentations/$id/slides/$slideId/regenerate': typeof ApiPresentationsIdSlidesSlideIdRegenerateRoute
  '/api/presentations/$id/slides/$slideId/visualize': typeof ApiPresentationsIdSlidesSlideIdVisualizeRoute
  '/api/presentations/$id/versions/$versionId/restore': typeof ApiPresentationsIdVersionsVersionIdRestoreRoute
  '/api/presentations/$id/slides/$slideId/': typeof ApiPresentationsIdSlidesSlideIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abou-us': typeof AbouUsRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/analytics': typeof AnalyticsRoute
  '/contact-us': typeof ContactUsRoute
  '/home': typeof HomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-and-cancellation-policy': typeof RefundAndCancellationPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/login': typeof AuthLoginRoute
  '/api/db-health': typeof ApiDbHealthRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/outline/$draftId': typeof OutlineDraftIdRoute
  '/present/$id': typeof PresentIdRoute
  '/presentation/$id': typeof PresentationIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/api/analytics/summary': typeof ApiAnalyticsSummaryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/me': typeof ApiBillingMeRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/brand-kits/$kitId': typeof ApiBrandKitsKitIdRoute
  '/api/health/system': typeof ApiHealthSystemRoute
  '/api/payment/create-order': typeof ApiPaymentCreateOrderRoute
  '/api/payment/verify': typeof ApiPaymentVerifyRoute
  '/api/presentations/history': typeof ApiPresentationsHistoryRoute
  '/api/presentations/import': typeof ApiPresentationsImportRoute
  '/api/presentations/outline': typeof ApiPresentationsOutlineRoute
  '/api/share/$token': typeof ApiShareTokenRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
  '/api/brand-kits': typeof ApiBrandKitsIndexRoute
  '/api/presentations': typeof ApiPresentationsIndexRoute
  '/api/drafts/$draftId/events': typeof ApiDraftsDraftIdEventsRoute
  '/api/drafts/$draftId/generate': typeof ApiDraftsDraftIdGenerateRoute
  '/api/drafts/$draftId/regenerate': typeof ApiDraftsDraftIdRegenerateRoute
  '/api/health/workers/$workerClass': typeof ApiHealthWorkersWorkerClassRoute
  '/api/presentations/$id/brand-kit': typeof ApiPresentationsIdBrandKitRoute
  '/api/presentations/$id/citation-mode': typeof ApiPresentationsIdCitationModeRoute
  '/api/presentations/$id/events': typeof ApiPresentationsIdEventsRoute
  '/api/presentations/$id/export': typeof ApiPresentationsIdExportRoute
  '/api/presentations/$id/members': typeof ApiPresentationsIdMembersRoute
  '/api/presentations/$id/share': typeof ApiPresentationsIdShareRoute
  '/api/presentations/$id/template': typeof ApiPresentationsIdTemplateRoute
  '/api/presentations/$id/text-actions': typeof ApiPresentationsIdTextActionsRoute
  '/api/drafts/$draftId': typeof ApiDraftsDraftIdIndexRoute
  '/api/health/workers': typeof ApiHealthWorkersIndexRoute
  '/api/presentations/$id': typeof ApiPresentationsIdIndexRoute
  '/api/drafts/$draftId/slides/$slideId': typeof ApiDraftsDraftIdSlidesSlideIdRoute
  '/api/presentations/$id/slides/reorder': typeof ApiPresentationsIdSlidesReorderRoute
  '/api/drafts/$draftId/slides': typeof ApiDraftsDraftIdSlidesIndexRoute
  '/api/presentations/$id/slides': typeof ApiPresentationsIdSlidesIndexRoute
  '/api/presentations/$id/versions': typeof ApiPresentationsIdVersionsIndexRoute
  '/api/presentations/$id/slides/$slideId/chat': typeof ApiPresentationsIdSlidesSlideIdChatRoute
  '/api/presentations/$id/slides/$slideId/duplicate': typeof ApiPresentationsIdSlidesSlideIdDuplicateRoute
  '/api/presentations/$id/slides/$slideId/image-regenerate': typeof ApiPresentationsIdSlidesSlideIdImageRegenerateRoute
  '/api/presentations/$id/slides/$slideId/image-upload': typeof ApiPresentationsIdSlidesSlideIdImageUploadRoute
  '/api/presentations/$id/slides/$slideId/regenerate': typeof ApiPresentationsIdSlidesSlideIdRegenerateRoute
  '/api/presentations/$id/slides/$slideId/visualize': typeof ApiPresentationsIdSlidesSlideIdVisualizeRoute
  '/api/presentations/$id/versions/$versionId/restore': typeof ApiPresentationsIdVersionsVersionIdRestoreRoute
  '/api/presentations/$id/slides/$slideId': typeof ApiPresentationsIdSlidesSlideIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/abou-us': typeof AbouUsRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/analytics': typeof AnalyticsRoute
  '/contact-us': typeof ContactUsRoute
  '/home': typeof HomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-and-cancellation-policy': typeof RefundAndCancellationPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/api/db-health': typeof ApiDbHealthRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/outline/$draftId': typeof OutlineDraftIdRoute
  '/present/$id': typeof PresentIdRoute
  '/presentation/$id': typeof PresentationIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/api/analytics/summary': typeof ApiAnalyticsSummaryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/me': typeof ApiBillingMeRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/brand-kits/$kitId': typeof ApiBrandKitsKitIdRoute
  '/api/health/system': typeof ApiHealthSystemRoute
  '/api/payment/create-order': typeof ApiPaymentCreateOrderRoute
  '/api/payment/verify': typeof ApiPaymentVerifyRoute
  '/api/presentations/history': typeof ApiPresentationsHistoryRoute
  '/api/presentations/import': typeof ApiPresentationsImportRoute
  '/api/presentations/outline': typeof ApiPresentationsOutlineRoute
  '/api/share/$token': typeof ApiShareTokenRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
  '/api/brand-kits/': typeof ApiBrandKitsIndexRoute
  '/api/presentations/': typeof ApiPresentationsIndexRoute
  '/api/drafts/$draftId/events': typeof ApiDraftsDraftIdEventsRoute
  '/api/drafts/$draftId/generate': typeof ApiDraftsDraftIdGenerateRoute
  '/api/drafts/$draftId/regenerate': typeof ApiDraftsDraftIdRegenerateRoute
  '/api/health/workers/$workerClass': typeof ApiHealthWorkersWorkerClassRoute
  '/api/presentations/$id/brand-kit': typeof ApiPresentationsIdBrandKitRoute
  '/api/presentations/$id/citation-mode': typeof ApiPresentationsIdCitationModeRoute
  '/api/presentations/$id/events': typeof ApiPresentationsIdEventsRoute
  '/api/presentations/$id/export': typeof ApiPresentationsIdExportRoute
  '/api/presentations/$id/members': typeof ApiPresentationsIdMembersRoute
  '/api/presentations/$id/share': typeof ApiPresentationsIdShareRoute
  '/api/presentations/$id/template': typeof ApiPresentationsIdTemplateRoute
  '/api/presentations/$id/text-actions': typeof ApiPresentationsIdTextActionsRoute
  '/api/drafts/$draftId/': typeof ApiDraftsDraftIdIndexRoute
  '/api/health/workers/': typeof ApiHealthWorkersIndexRoute
  '/api/presentations/$id/': typeof ApiPresentationsIdIndexRoute
  '/api/drafts/$draftId/slides/$slideId': typeof ApiDraftsDraftIdSlidesSlideIdRoute
  '/api/presentations/$id/slides/reorder': typeof ApiPresentationsIdSlidesReorderRoute
  '/api/drafts/$draftId/slides/': typeof ApiDraftsDraftIdSlidesIndexRoute
  '/api/presentations/$id/slides/': typeof ApiPresentationsIdSlidesIndexRoute
  '/api/presentations/$id/versions/': typeof ApiPresentationsIdVersionsIndexRoute
  '/api/presentations/$id/slides/$slideId/chat': typeof ApiPresentationsIdSlidesSlideIdChatRoute
  '/api/presentations/$id/slides/$slideId/duplicate': typeof ApiPresentationsIdSlidesSlideIdDuplicateRoute
  '/api/presentations/$id/slides/$slideId/image-regenerate': typeof ApiPresentationsIdSlidesSlideIdImageRegenerateRoute
  '/api/presentations/$id/slides/$slideId/image-upload': typeof ApiPresentationsIdSlidesSlideIdImageUploadRoute
  '/api/presentations/$id/slides/$slideId/regenerate': typeof ApiPresentationsIdSlidesSlideIdRegenerateRoute
  '/api/presentations/$id/slides/$slideId/visualize': typeof ApiPresentationsIdSlidesSlideIdVisualizeRoute
  '/api/presentations/$id/versions/$versionId/restore': typeof ApiPresentationsIdVersionsVersionIdRestoreRoute
  '/api/presentations/$id/slides/$slideId/': typeof ApiPresentationsIdSlidesSlideIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abou-us'
    | '/about'
    | '/about-us'
    | '/analytics'
    | '/contact-us'
    | '/home'
    | '/privacy-policy'
    | '/refund-and-cancellation-policy'
    | '/terms-and-conditions'
    | '/login'
    | '/api/db-health'
    | '/api/metrics'
    | '/outline/$draftId'
    | '/present/$id'
    | '/presentation/$id'
    | '/share/$token'
    | '/api/analytics/summary'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/me'
    | '/api/billing/portal'
    | '/api/brand-kits/$kitId'
    | '/api/health/system'
    | '/api/payment/create-order'
    | '/api/payment/verify'
    | '/api/presentations/history'
    | '/api/presentations/import'
    | '/api/presentations/outline'
    | '/api/share/$token'
    | '/api/webhooks/paddle'
    | '/api/brand-kits/'
    | '/api/presentations/'
    | '/api/drafts/$draftId/events'
    | '/api/drafts/$draftId/generate'
    | '/api/drafts/$draftId/regenerate'
    | '/api/health/workers/$workerClass'
    | '/api/presentations/$id/brand-kit'
    | '/api/presentations/$id/citation-mode'
    | '/api/presentations/$id/events'
    | '/api/presentations/$id/export'
    | '/api/presentations/$id/members'
    | '/api/presentations/$id/share'
    | '/api/presentations/$id/template'
    | '/api/presentations/$id/text-actions'
    | '/api/drafts/$draftId/'
    | '/api/health/workers/'
    | '/api/presentations/$id/'
    | '/api/drafts/$draftId/slides/$slideId'
    | '/api/presentations/$id/slides/reorder'
    | '/api/drafts/$draftId/slides/'
    | '/api/presentations/$id/slides/'
    | '/api/presentations/$id/versions/'
    | '/api/presentations/$id/slides/$slideId/chat'
    | '/api/presentations/$id/slides/$slideId/duplicate'
    | '/api/presentations/$id/slides/$slideId/image-regenerate'
    | '/api/presentations/$id/slides/$slideId/image-upload'
    | '/api/presentations/$id/slides/$slideId/regenerate'
    | '/api/presentations/$id/slides/$slideId/visualize'
    | '/api/presentations/$id/versions/$versionId/restore'
    | '/api/presentations/$id/slides/$slideId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abou-us'
    | '/about'
    | '/about-us'
    | '/analytics'
    | '/contact-us'
    | '/home'
    | '/privacy-policy'
    | '/refund-and-cancellation-policy'
    | '/terms-and-conditions'
    | '/login'
    | '/api/db-health'
    | '/api/metrics'
    | '/outline/$draftId'
    | '/present/$id'
    | '/presentation/$id'
    | '/share/$token'
    | '/api/analytics/summary'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/me'
    | '/api/billing/portal'
    | '/api/brand-kits/$kitId'
    | '/api/health/system'
    | '/api/payment/create-order'
    | '/api/payment/verify'
    | '/api/presentations/history'
    | '/api/presentations/import'
    | '/api/presentations/outline'
    | '/api/share/$token'
    | '/api/webhooks/paddle'
    | '/api/brand-kits'
    | '/api/presentations'
    | '/api/drafts/$draftId/events'
    | '/api/drafts/$draftId/generate'
    | '/api/drafts/$draftId/regenerate'
    | '/api/health/workers/$workerClass'
    | '/api/presentations/$id/brand-kit'
    | '/api/presentations/$id/citation-mode'
    | '/api/presentations/$id/events'
    | '/api/presentations/$id/export'
    | '/api/presentations/$id/members'
    | '/api/presentations/$id/share'
    | '/api/presentations/$id/template'
    | '/api/presentations/$id/text-actions'
    | '/api/drafts/$draftId'
    | '/api/health/workers'
    | '/api/presentations/$id'
    | '/api/drafts/$draftId/slides/$slideId'
    | '/api/presentations/$id/slides/reorder'
    | '/api/drafts/$draftId/slides'
    | '/api/presentations/$id/slides'
    | '/api/presentations/$id/versions'
    | '/api/presentations/$id/slides/$slideId/chat'
    | '/api/presentations/$id/slides/$slideId/duplicate'
    | '/api/presentations/$id/slides/$slideId/image-regenerate'
    | '/api/presentations/$id/slides/$slideId/image-upload'
    | '/api/presentations/$id/slides/$slideId/regenerate'
    | '/api/presentations/$id/slides/$slideId/visualize'
    | '/api/presentations/$id/versions/$versionId/restore'
    | '/api/presentations/$id/slides/$slideId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/abou-us'
    | '/about'
    | '/about-us'
    | '/analytics'
    | '/contact-us'
    | '/home'
    | '/privacy-policy'
    | '/refund-and-cancellation-policy'
    | '/terms-and-conditions'
    | '/_auth/login'
    | '/api/db-health'
    | '/api/metrics'
    | '/outline/$draftId'
    | '/present/$id'
    | '/presentation/$id'
    | '/share/$token'
    | '/api/analytics/summary'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/me'
    | '/api/billing/portal'
    | '/api/brand-kits/$kitId'
    | '/api/health/system'
    | '/api/payment/create-order'
    | '/api/payment/verify'
    | '/api/presentations/history'
    | '/api/presentations/import'
    | '/api/presentations/outline'
    | '/api/share/$token'
    | '/api/webhooks/paddle'
    | '/api/brand-kits/'
    | '/api/presentations/'
    | '/api/drafts/$draftId/events'
    | '/api/drafts/$draftId/generate'
    | '/api/drafts/$draftId/regenerate'
    | '/api/health/workers/$workerClass'
    | '/api/presentations/$id/brand-kit'
    | '/api/presentations/$id/citation-mode'
    | '/api/presentations/$id/events'
    | '/api/presentations/$id/export'
    | '/api/presentations/$id/members'
    | '/api/presentations/$id/share'
    | '/api/presentations/$id/template'
    | '/api/presentations/$id/text-actions'
    | '/api/drafts/$draftId/'
    | '/api/health/workers/'
    | '/api/presentations/$id/'
    | '/api/drafts/$draftId/slides/$slideId'
    | '/api/presentations/$id/slides/reorder'
    | '/api/drafts/$draftId/slides/'
    | '/api/presentations/$id/slides/'
    | '/api/presentations/$id/versions/'
    | '/api/presentations/$id/slides/$slideId/chat'
    | '/api/presentations/$id/slides/$slideId/duplicate'
    | '/api/presentations/$id/slides/$slideId/image-regenerate'
    | '/api/presentations/$id/slides/$slideId/image-upload'
    | '/api/presentations/$id/slides/$slideId/regenerate'
    | '/api/presentations/$id/slides/$slideId/visualize'
    | '/api/presentations/$id/versions/$versionId/restore'
    | '/api/presentations/$id/slides/$slideId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AbouUsRoute: typeof AbouUsRoute
  AboutRoute: typeof AboutRoute
  AboutUsRoute: typeof AboutUsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ContactUsRoute: typeof ContactUsRoute
  HomeRoute: typeof HomeRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundAndCancellationPolicyRoute: typeof RefundAndCancellationPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ApiDbHealthRoute: typeof ApiDbHealthRoute
  ApiMetricsRoute: typeof ApiMetricsRoute
  OutlineDraftIdRoute: typeof OutlineDraftIdRoute
  PresentIdRoute: typeof PresentIdRoute
  PresentationIdRoute: typeof PresentationIdRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiAnalyticsSummaryRoute: typeof ApiAnalyticsSummaryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingMeRoute: typeof ApiBillingMeRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiBrandKitsKitIdRoute: typeof ApiBrandKitsKitIdRoute
  ApiHealthSystemRoute: typeof ApiHealthSystemRoute
  ApiPaymentCreateOrderRoute: typeof ApiPaymentCreateOrderRoute
  ApiPaymentVerifyRoute: typeof ApiPaymentVerifyRoute
  ApiPresentationsHistoryRoute: typeof ApiPresentationsHistoryRoute
  ApiPresentationsImportRoute: typeof ApiPresentationsImportRoute
  ApiPresentationsOutlineRoute: typeof ApiPresentationsOutlineRoute
  ApiShareTokenRoute: typeof ApiShareTokenRoute
  ApiWebhooksPaddleRoute: typeof ApiWebhooksPaddleRoute
  ApiBrandKitsIndexRoute: typeof ApiBrandKitsIndexRoute
  ApiPresentationsIndexRoute: typeof ApiPresentationsIndexRoute
  ApiDraftsDraftIdEventsRoute: typeof ApiDraftsDraftIdEventsRoute
  ApiDraftsDraftIdGenerateRoute: typeof ApiDraftsDraftIdGenerateRoute
  ApiDraftsDraftIdRegenerateRoute: typeof ApiDraftsDraftIdRegenerateRoute
  ApiHealthWorkersWorkerClassRoute: typeof ApiHealthWorkersWorkerClassRoute
  ApiPresentationsIdBrandKitRoute: typeof ApiPresentationsIdBrandKitRoute
  ApiPresentationsIdCitationModeRoute: typeof ApiPresentationsIdCitationModeRoute
  ApiPresentationsIdEventsRoute: typeof ApiPresentationsIdEventsRoute
  ApiPresentationsIdExportRoute: typeof ApiPresentationsIdExportRoute
  ApiPresentationsIdMembersRoute: typeof ApiPresentationsIdMembersRoute
  ApiPresentationsIdShareRoute: typeof ApiPresentationsIdShareRoute
  ApiPresentationsIdTemplateRoute: typeof ApiPresentationsIdTemplateRoute
  ApiPresentationsIdTextActionsRoute: typeof ApiPresentationsIdTextActionsRoute
  ApiDraftsDraftIdIndexRoute: typeof ApiDraftsDraftIdIndexRoute
  ApiHealthWorkersIndexRoute: typeof ApiHealthWorkersIndexRoute
  ApiPresentationsIdIndexRoute: typeof ApiPresentationsIdIndexRoute
  ApiDraftsDraftIdSlidesSlideIdRoute: typeof ApiDraftsDraftIdSlidesSlideIdRoute
  ApiPresentationsIdSlidesReorderRoute: typeof ApiPresentationsIdSlidesReorderRoute
  ApiDraftsDraftIdSlidesIndexRoute: typeof ApiDraftsDraftIdSlidesIndexRoute
  ApiPresentationsIdSlidesIndexRoute: typeof ApiPresentationsIdSlidesIndexRoute
  ApiPresentationsIdVersionsIndexRoute: typeof ApiPresentationsIdVersionsIndexRoute
  ApiPresentationsIdSlidesSlideIdChatRoute: typeof ApiPresentationsIdSlidesSlideIdChatRoute
  ApiPresentationsIdSlidesSlideIdDuplicateRoute: typeof ApiPresentationsIdSlidesSlideIdDuplicateRoute
  ApiPresentationsIdSlidesSlideIdImageRegenerateRoute: typeof ApiPresentationsIdSlidesSlideIdImageRegenerateRoute
  ApiPresentationsIdSlidesSlideIdImageUploadRoute: typeof ApiPresentationsIdSlidesSlideIdImageUploadRoute
  ApiPresentationsIdSlidesSlideIdRegenerateRoute: typeof ApiPresentationsIdSlidesSlideIdRegenerateRoute
  ApiPresentationsIdSlidesSlideIdVisualizeRoute: typeof ApiPresentationsIdSlidesSlideIdVisualizeRoute
  ApiPresentationsIdVersionsVersionIdRestoreRoute: typeof ApiPresentationsIdVersionsVersionIdRestoreRoute
  ApiPresentationsIdSlidesSlideIdIndexRoute: typeof ApiPresentationsIdSlidesSlideIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-and-cancellation-policy': {
      id: '/refund-and-cancellation-policy'
      path: '/refund-and-cancellation-policy'
      fullPath: '/refund-and-cancellation-policy'
      preLoaderRoute: typeof RefundAndCancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abou-us': {
      id: '/abou-us'
      path: '/abou-us'
      fullPath: '/abou-us'
      preLoaderRoute: typeof AbouUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation/$id': {
      id: '/presentation/$id'
      path: '/presentation/$id'
      fullPath: '/presentation/$id'
      preLoaderRoute: typeof PresentationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$id': {
      id: '/present/$id'
      path: '/present/$id'
      fullPath: '/present/$id'
      preLoaderRoute: typeof PresentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outline/$draftId': {
      id: '/outline/$draftId'
      path: '/outline/$draftId'
      fullPath: '/outline/$draftId'
      preLoaderRoute: typeof OutlineDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metrics': {
      id: '/api/metrics'
      path: '/api/metrics'
      fullPath: '/api/metrics'
      preLoaderRoute: typeof ApiMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db-health': {
      id: '/api/db-health'
      path: '/api/db-health'
      fullPath: '/api/db-health'
      preLoaderRoute: typeof ApiDbHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/presentations/': {
      id: '/api/presentations/'
      path: '/api/presentations'
      fullPath: '/api/presentations/'
      preLoaderRoute: typeof ApiPresentationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-kits/': {
      id: '/api/brand-kits/'
      path: '/api/brand-kits'
      fullPath: '/api/brand-kits/'
      preLoaderRoute: typeof ApiBrandKitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/paddle': {
      id: '/api/webhooks/paddle'
      path: '/api/webhooks/paddle'
      fullPath: '/api/webhooks/paddle'
      preLoaderRoute: typeof ApiWebhooksPaddleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/$token': {
      id: '/api/share/$token'
      path: '/api/share/$token'
      fullPath: '/api/share/$token'
      preLoaderRoute: typeof ApiShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/outline': {
      id: '/api/presentations/outline'
      path: '/api/presentations/outline'
      fullPath: '/api/presentations/outline'
      preLoaderRoute: typeof ApiPresentationsOutlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/import': {
      id: '/api/presentations/import'
      path: '/api/presentations/import'
      fullPath: '/api/presentations/import'
      preLoaderRoute: typeof ApiPresentationsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/history': {
      id: '/api/presentations/history'
      path: '/api/presentations/history'
      fullPath: '/api/presentations/history'
      preLoaderRoute: typeof ApiPresentationsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/verify': {
      id: '/api/payment/verify'
      path: '/api/payment/verify'
      fullPath: '/api/payment/verify'
      preLoaderRoute: typeof ApiPaymentVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/create-order': {
      id: '/api/payment/create-order'
      path: '/api/payment/create-order'
      fullPath: '/api/payment/create-order'
      preLoaderRoute: typeof ApiPaymentCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/system': {
      id: '/api/health/system'
      path: '/api/health/system'
      fullPath: '/api/health/system'
      preLoaderRoute: typeof ApiHealthSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-kits/$kitId': {
      id: '/api/brand-kits/$kitId'
      path: '/api/brand-kits/$kitId'
      fullPath: '/api/brand-kits/$kitId'
      preLoaderRoute: typeof ApiBrandKitsKitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/portal': {
      id: '/api/billing/portal'
      path: '/api/billing/portal'
      fullPath: '/api/billing/portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/me': {
      id: '/api/billing/me'
      path: '/api/billing/me'
      fullPath: '/api/billing/me'
      preLoaderRoute: typeof ApiBillingMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/summary': {
      id: '/api/analytics/summary'
      path: '/api/analytics/summary'
      fullPath: '/api/analytics/summary'
      preLoaderRoute: typeof ApiAnalyticsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/': {
      id: '/api/presentations/$id/'
      path: '/api/presentations/$id'
      fullPath: '/api/presentations/$id/'
      preLoaderRoute: typeof ApiPresentationsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/workers/': {
      id: '/api/health/workers/'
      path: '/api/health/workers'
      fullPath: '/api/health/workers/'
      preLoaderRoute: typeof ApiHealthWorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drafts/$draftId/': {
      id: '/api/drafts/$draftId/'
      path: '/api/drafts/$draftId'
      fullPath: '/api/drafts/$draftId/'
      preLoaderRoute: typeof ApiDraftsDraftIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/text-actions': {
      id: '/api/presentations/$id/text-actions'
      path: '/api/presentations/$id/text-actions'
      fullPath: '/api/presentations/$id/text-actions'
      preLoaderRoute: typeof ApiPresentationsIdTextActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/template': {
      id: '/api/presentations/$id/template'
      path: '/api/presentations/$id/template'
      fullPath: '/api/presentations/$id/template'
      preLoaderRoute: typeof ApiPresentationsIdTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/share': {
      id: '/api/presentations/$id/share'
      path: '/api/presentations/$id/share'
      fullPath: '/api/presentations/$id/share'
      preLoaderRoute: typeof ApiPresentationsIdShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/members': {
      id: '/api/presentations/$id/members'
      path: '/api/presentations/$id/members'
      fullPath: '/api/presentations/$id/members'
      preLoaderRoute: typeof ApiPresentationsIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/export': {
      id: '/api/presentations/$id/export'
      path: '/api/presentations/$id/export'
      fullPath: '/api/presentations/$id/export'
      preLoaderRoute: typeof ApiPresentationsIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/events': {
      id: '/api/presentations/$id/events'
      path: '/api/presentations/$id/events'
      fullPath: '/api/presentations/$id/events'
      preLoaderRoute: typeof ApiPresentationsIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/citation-mode': {
      id: '/api/presentations/$id/citation-mode'
      path: '/api/presentations/$id/citation-mode'
      fullPath: '/api/presentations/$id/citation-mode'
      preLoaderRoute: typeof ApiPresentationsIdCitationModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/brand-kit': {
      id: '/api/presentations/$id/brand-kit'
      path: '/api/presentations/$id/brand-kit'
      fullPath: '/api/presentations/$id/brand-kit'
      preLoaderRoute: typeof ApiPresentationsIdBrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/workers/$workerClass': {
      id: '/api/health/workers/$workerClass'
      path: '/api/health/workers/$workerClass'
      fullPath: '/api/health/workers/$workerClass'
      preLoaderRoute: typeof ApiHealthWorkersWorkerClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drafts/$draftId/regenerate': {
      id: '/api/drafts/$draftId/regenerate'
      path: '/api/drafts/$draftId/regenerate'
      fullPath: '/api/drafts/$draftId/regenerate'
      preLoaderRoute: typeof ApiDraftsDraftIdRegenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drafts/$draftId/generate': {
      id: '/api/drafts/$draftId/generate'
      path: '/api/drafts/$draftId/generate'
      fullPath: '/api/drafts/$draftId/generate'
      preLoaderRoute: typeof ApiDraftsDraftIdGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drafts/$draftId/events': {
      id: '/api/drafts/$draftId/events'
      path: '/api/drafts/$draftId/events'
      fullPath: '/api/drafts/$draftId/events'
      preLoaderRoute: typeof ApiDraftsDraftIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/versions/': {
      id: '/api/presentations/$id/versions/'
      path: '/api/presentations/$id/versions'
      fullPath: '/api/presentations/$id/versions/'
      preLoaderRoute: typeof ApiPresentationsIdVersionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/slides/': {
      id: '/api/presentations/$id/slides/'
      path: '/api/presentations/$id/slides'
      fullPath: '/api/presentations/$id/slides/'
      preLoaderRoute: typeof ApiPresentationsIdSlidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drafts/$draftId/slides/': {
      id: '/api/drafts/$draftId/slides/'
      path: '/api/drafts/$draftId/slides'
      fullPath: '/api/drafts/$draftId/slides/'
      preLoaderRoute: typeof ApiDraftsDraftIdSlidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/slides/reorder': {
      id: '/api/presentations/$id/slides/reorder'
      path: '/api/presentations/$id/slides/reorder'
      fullPath: '/api/presentations/$id/slides/reorder'
      preLoaderRoute: typeof ApiPresentationsIdSlidesReorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drafts/$draftId/slides/$slideId': {
      id: '/api/drafts/$draftId/slides/$slideId'
      path: '/api/drafts/$draftId/slides/$slideId'
      fullPath: '/api/drafts/$draftId/slides/$slideId'
      preLoaderRoute: typeof ApiDraftsDraftIdSlidesSlideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/slides/$slideId/': {
      id: '/api/presentations/$id/slides/$slideId/'
      path: '/api/presentations/$id/slides/$slideId'
      fullPath: '/api/presentations/$id/slides/$slideId/'
      preLoaderRoute: typeof ApiPresentationsIdSlidesSlideIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/versions/$versionId/restore': {
      id: '/api/presentations/$id/versions/$versionId/restore'
      path: '/api/presentations/$id/versions/$versionId/restore'
      fullPath: '/api/presentations/$id/versions/$versionId/restore'
      preLoaderRoute: typeof ApiPresentationsIdVersionsVersionIdRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/slides/$slideId/visualize': {
      id: '/api/presentations/$id/slides/$slideId/visualize'
      path: '/api/presentations/$id/slides/$slideId/visualize'
      fullPath: '/api/presentations/$id/slides/$slideId/visualize'
      preLoaderRoute: typeof ApiPresentationsIdSlidesSlideIdVisualizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/slides/$slideId/regenerate': {
      id: '/api/presentations/$id/slides/$slideId/regenerate'
      path: '/api/presentations/$id/slides/$slideId/regenerate'
      fullPath: '/api/presentations/$id/slides/$slideId/regenerate'
      preLoaderRoute: typeof ApiPresentationsIdSlidesSlideIdRegenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/slides/$slideId/image-upload': {
      id: '/api/presentations/$id/slides/$slideId/image-upload'
      path: '/api/presentations/$id/slides/$slideId/image-upload'
      fullPath: '/api/presentations/$id/slides/$slideId/image-upload'
      preLoaderRoute: typeof ApiPresentationsIdSlidesSlideIdImageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/slides/$slideId/image-regenerate': {
      id: '/api/presentations/$id/slides/$slideId/image-regenerate'
      path: '/api/presentations/$id/slides/$slideId/image-regenerate'
      fullPath: '/api/presentations/$id/slides/$slideId/image-regenerate'
      preLoaderRoute: typeof ApiPresentationsIdSlidesSlideIdImageRegenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/slides/$slideId/duplicate': {
      id: '/api/presentations/$id/slides/$slideId/duplicate'
      path: '/api/presentations/$id/slides/$slideId/duplicate'
      fullPath: '/api/presentations/$id/slides/$slideId/duplicate'
      preLoaderRoute: typeof ApiPresentationsIdSlidesSlideIdDuplicateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations/$id/slides/$slideId/chat': {
      id: '/api/presentations/$id/slides/$slideId/chat'
      path: '/api/presentations/$id/slides/$slideId/chat'
      fullPath: '/api/presentations/$id/slides/$slideId/chat'
      preLoaderRoute: typeof ApiPresentationsIdSlidesSlideIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AbouUsRoute: AbouUsRoute,
  AboutRoute: AboutRoute,
  AboutUsRoute: AboutUsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ContactUsRoute: ContactUsRoute,
  HomeRoute: HomeRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundAndCancellationPolicyRoute: RefundAndCancellationPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ApiDbHealthRoute: ApiDbHealthRoute,
  ApiMetricsRoute: ApiMetricsRoute,
  OutlineDraftIdRoute: OutlineDraftIdRoute,
  PresentIdRoute: PresentIdRoute,
  PresentationIdRoute: PresentationIdRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiAnalyticsSummaryRoute: ApiAnalyticsSummaryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingMeRoute: ApiBillingMeRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiBrandKitsKitIdRoute: ApiBrandKitsKitIdRoute,
  ApiHealthSystemRoute: ApiHealthSystemRoute,
  ApiPaymentCreateOrderRoute: ApiPaymentCreateOrderRoute,
  ApiPaymentVerifyRoute: ApiPaymentVerifyRoute,
  ApiPresentationsHistoryRoute: ApiPresentationsHistoryRoute,
  ApiPresentationsImportRoute: ApiPresentationsImportRoute,
  ApiPresentationsOutlineRoute: ApiPresentationsOutlineRoute,
  ApiShareTokenRoute: ApiShareTokenRoute,
  ApiWebhooksPaddleRoute: ApiWebhooksPaddleRoute,
  ApiBrandKitsIndexRoute: ApiBrandKitsIndexRoute,
  ApiPresentationsIndexRoute: ApiPresentationsIndexRoute,
  ApiDraftsDraftIdEventsRoute: ApiDraftsDraftIdEventsRoute,
  ApiDraftsDraftIdGenerateRoute: ApiDraftsDraftIdGenerateRoute,
  ApiDraftsDraftIdRegenerateRoute: ApiDraftsDraftIdRegenerateRoute,
  ApiHealthWorkersWorkerClassRoute: ApiHealthWorkersWorkerClassRoute,
  ApiPresentationsIdBrandKitRoute: ApiPresentationsIdBrandKitRoute,
  ApiPresentationsIdCitationModeRoute: ApiPresentationsIdCitationModeRoute,
  ApiPresentationsIdEventsRoute: ApiPresentationsIdEventsRoute,
  ApiPresentationsIdExportRoute: ApiPresentationsIdExportRoute,
  ApiPresentationsIdMembersRoute: ApiPresentationsIdMembersRoute,
  ApiPresentationsIdShareRoute: ApiPresentationsIdShareRoute,
  ApiPresentationsIdTemplateRoute: ApiPresentationsIdTemplateRoute,
  ApiPresentationsIdTextActionsRoute: ApiPresentationsIdTextActionsRoute,
  ApiDraftsDraftIdIndexRoute: ApiDraftsDraftIdIndexRoute,
  ApiHealthWorkersIndexRoute: ApiHealthWorkersIndexRoute,
  ApiPresentationsIdIndexRoute: ApiPresentationsIdIndexRoute,
  ApiDraftsDraftIdSlidesSlideIdRoute: ApiDraftsDraftIdSlidesSlideIdRoute,
  ApiPresentationsIdSlidesReorderRoute: ApiPresentationsIdSlidesReorderRoute,
  ApiDraftsDraftIdSlidesIndexRoute: ApiDraftsDraftIdSlidesIndexRoute,
  ApiPresentationsIdSlidesIndexRoute: ApiPresentationsIdSlidesIndexRoute,
  ApiPresentationsIdVersionsIndexRoute: ApiPresentationsIdVersionsIndexRoute,
  ApiPresentationsIdSlidesSlideIdChatRoute:
    ApiPresentationsIdSlidesSlideIdChatRoute,
  ApiPresentationsIdSlidesSlideIdDuplicateRoute:
    ApiPresentationsIdSlidesSlideIdDuplicateRoute,
  ApiPresentationsIdSlidesSlideIdImageRegenerateRoute:
    ApiPresentationsIdSlidesSlideIdImageRegenerateRoute,
  ApiPresentationsIdSlidesSlideIdImageUploadRoute:
    ApiPresentationsIdSlidesSlideIdImageUploadRoute,
  ApiPresentationsIdSlidesSlideIdRegenerateRoute:
    ApiPresentationsIdSlidesSlideIdRegenerateRoute,
  ApiPresentationsIdSlidesSlideIdVisualizeRoute:
    ApiPresentationsIdSlidesSlideIdVisualizeRoute,
  ApiPresentationsIdVersionsVersionIdRestoreRoute:
    ApiPresentationsIdVersionsVersionIdRestoreRoute,
  ApiPresentationsIdSlidesSlideIdIndexRoute:
    ApiPresentationsIdSlidesSlideIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
