import OutlineSlideList from '@/components/outline/OutlineSlideList'
import OutlineToolbar from '@/components/outline/OutlineToolbar'
import type { OutlineDraft, OutlineSlide } from '@/components/outline/types'
import { Button } from '@/components/ui/button'
import { Spinner } from '@/components/ui/spinner'
import { AUTH_LOGIN_PATH } from '@/lib/auth-path'
import { getSession } from '@/lib/auth-function'
import { createFileRoute, redirect, useNavigate } from '@tanstack/react-router'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { toast } from 'sonner'

export const Route = createFileRoute('/outline/$draftId')({
  beforeLoad: async ({ location }) => {
    const session = await getSession()
    if (!session) {
      throw redirect({
        to: AUTH_LOGIN_PATH,
        search: { redirect: location.href },
      })
    }
  },
  component: OutlineRouteComponent,
})

function reorderLocalSlides(slides: OutlineSlide[], slideIds: string[]) {
  const lookup = new Map(slides.map((slide) => [slide.id, slide]))
  return slideIds
    .map((id, index) => {
      const slide = lookup.get(id)
      if (!slide) return null
      return {
        ...slide,
        position: index,
      }
    })
    .filter((slide): slide is OutlineSlide => slide !== null)
}

function OutlineRouteComponent() {
  const { draftId } = Route.useParams()
  const navigate = useNavigate()

  const [draft, setDraft] = useState<OutlineDraft | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const [savingSlideId, setSavingSlideId] = useState<string | null>(null)
  const [isRegenerating, setIsRegenerating] = useState(false)
  const [isGeneratingPresentation, setIsGeneratingPresentation] = useState(false)
  const [outlineError, setOutlineError] = useState<string | null>(null)

  const saveTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const loadDraft = useCallback(async () => {
    try {
      setIsLoading(true)
      const response = await fetch(`/api/drafts/${draftId}/`)
      const payload = (await response.json()) as OutlineDraft | { error: string }
      if (!response.ok || 'error' in payload) {
        throw new Error(
          'error' in payload ? payload.error : 'Could not load draft outline.',
        )
      }
      setDraft(payload)
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Could not load draft.')
    } finally {
      setIsLoading(false)
    }
  }, [draftId])

  useEffect(() => {
    void loadDraft()
  }, [loadDraft])

  // While the outline is still being generated by the worker, watch progress
  // over SSE and refetch the full draft (slides + title) once it's ready.
  const draftStatus = draft?.status
  useEffect(() => {
    if (draftStatus !== 'OUTLINE_PENDING' && draftStatus !== 'OUTLINE_GENERATING') return

    const source = new EventSource(`/api/drafts/${draftId}/events`)

    const handleStatus = (status: OutlineDraft['status'], error?: string) => {
      if (status === 'OUTLINE_GENERATING') {
        setDraft((cur) => (cur ? { ...cur, status } : cur))
      } else if (status === 'OUTLINE_READY') {
        source.close()
        void loadDraft()
      } else if (status === 'OUTLINE_FAILED') {
        source.close()
        setOutlineError(error ?? 'Outline generation failed. Please try again.')
        setDraft((cur) => (cur ? { ...cur, status } : cur))
      }
    }

    source.addEventListener('snapshot', (e) => {
      if (!(e instanceof MessageEvent)) return
      const payload = JSON.parse(e.data) as OutlineDraft
      if (payload.status === 'OUTLINE_READY') {
        source.close()
        setDraft(payload)
      } else {
        handleStatus(payload.status)
      }
    })

    source.addEventListener('progress', (e) => {
      if (!(e instanceof MessageEvent)) return
      const payload = JSON.parse(e.data) as { status?: OutlineDraft['status']; error?: string }
      if (payload.status) handleStatus(payload.status, payload.error)
    })

    source.onerror = () => source.close()
    return () => source.close()
  }, [draftStatus, draftId, loadDraft])

  const saveSlide = useCallback(
    async (slide: OutlineSlide) => {
      setSavingSlideId(slide.id)
      try {
        const response = await fetch(`/api/drafts/${draftId}/`, {
          method: 'PATCH',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({
            action: 'update-slide',
            slideId: slide.id,
            data: {
              title: slide.title.trim(),
              intent: slide.intent.trim(),
              bullets: slide.bullets,
              visualConcept: slide.visualConcept.trim(),
              speakerNotesHint: slide.speakerNotesHint,
            },
          }),
        })
        if (!response.ok) {
          throw new Error('Failed to save slide changes.')
        }
      } catch {
        toast.error('Could not save this slide yet. Please retry.')
      } finally {
        setSavingSlideId(null)
      }
    },
    [draftId],
  )

  const handleSlideChange = useCallback(
    (nextSlide: OutlineSlide) => {
      setDraft((current) => {
        if (!current) return current
        return {
          ...current,
          slides: current.slides.map((slide) =>
            slide.id === nextSlide.id ? nextSlide : slide,
          ),
        }
      })

      if (saveTimeoutRef.current) {
        clearTimeout(saveTimeoutRef.current)
      }
      saveTimeoutRef.current = setTimeout(() => {
        void saveSlide(nextSlide)
      }, 500)
    },
    [saveSlide],
  )

  const handleReorder = useCallback(
    async (slideIds: string[]) => {
      setDraft((current) => {
        if (!current) return current
        return {
          ...current,
          slides: reorderLocalSlides(current.slides, slideIds),
        }
      })

      try {
        const response = await fetch(`/api/drafts/${draftId}/`, {
          method: 'PATCH',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({
            action: 'reorder',
            slideIds,
          }),
        })
        if (!response.ok) {
          throw new Error('Failed to reorder slides.')
        }
      } catch {
        toast.error('Could not reorder slides. Refresh and try again.')
      }
    },
    [draftId],
  )

  const handleDeleteSlide = useCallback(
    async (slideId: string) => {
      try {
        const response = await fetch(`/api/drafts/${draftId}/slides/${slideId}`, {
          method: 'DELETE',
        })
        const payload = (await response.json()) as OutlineDraft | { error: string }
        if (!response.ok || 'error' in payload) {
          throw new Error(
            'error' in payload ? payload.error : 'Could not delete this slide.',
          )
        }
        setDraft(payload)
      } catch (error) {
        toast.error(error instanceof Error ? error.message : 'Could not delete slide.')
      }
    },
    [draftId],
  )

  const handleAddSlide = useCallback(async () => {
    try {
      const response = await fetch(`/api/drafts/${draftId}/slides/`, {
        method: 'POST',
      })
      const payload = (await response.json()) as OutlineDraft | { error: string }
      if (!response.ok || 'error' in payload) {
        throw new Error(
          'error' in payload ? payload.error : 'Could not add a new slide.',
        )
      }
      setDraft(payload)
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Could not add slide.')
    }
  }, [draftId])

  const handleRegenerate = useCallback(async () => {
    try {
      setIsRegenerating(true)
      const response = await fetch(`/api/drafts/${draftId}/regenerate`, {
        method: 'POST',
      })
      const payload = (await response.json()) as OutlineDraft | { error: string }
      if (!response.ok || 'error' in payload) {
        throw new Error(
          'error' in payload ? payload.error : 'Outline regeneration failed.',
        )
      }
      setDraft(payload)
      toast.success('Outline regenerated.')
    } catch (error) {
      toast.error(
        error instanceof Error ? error.message : 'Could not regenerate outline.',
      )
    } finally {
      setIsRegenerating(false)
    }
  }, [draftId])

  const handleGeneratePresentation = useCallback(async () => {
    try {
      setIsGeneratingPresentation(true)
      const response = await fetch(`/api/drafts/${draftId}/generate`, {
        method: 'POST',
      })
      const payload = (await response.json()) as
        | { presentationId: string }
        | { error: string }
      if (!response.ok || 'error' in payload) {
        throw new Error(
          'error' in payload ? payload.error : 'Could not start presentation generation.',
        )
      }
      await navigate({ to: '/presentation/$id', params: { id: payload.presentationId } })
    } catch (error) {
      toast.error(
        error instanceof Error ? error.message : 'Could not queue generation jobs.',
      )
    } finally {
      setIsGeneratingPresentation(false)
    }
  }, [draftId, navigate])

  const slideCountLabel = useMemo(() => {
    if (!draft) return ''
    return `${draft.slides.length} slides in outline`
  }, [draft])

  if (isLoading) {
    return (
      <main className="mx-auto max-w-6xl px-4 pb-16 pt-24 sm:px-6 lg:px-8">
        <p className="text-sm text-muted-foreground">Loading outline...</p>
      </main>
    )
  }

  if (!draft) {
    return (
      <main className="mx-auto max-w-6xl px-4 pb-16 pt-24 sm:px-6 lg:px-8">
        <p className="text-sm text-muted-foreground">
          Draft not found. Return to home and try again.
        </p>
      </main>
    )
  }

  if (draft.status === 'OUTLINE_PENDING' || draft.status === 'OUTLINE_GENERATING') {
    return (
      <main className="mx-auto flex max-w-6xl flex-col items-center justify-center px-4 pb-16 pt-32 text-center sm:px-6 lg:px-8">
        <Spinner className="size-8 text-primary" />
        <h1 className="mt-6 text-xl font-semibold">Generating your outline…</h1>
        <p className="mt-2 max-w-md text-sm text-muted-foreground">
          Our AI is drafting a structured outline for “{draft.title}”. This usually takes a few
          seconds — you can stay on this page.
        </p>
        <div className="mt-8 w-full max-w-2xl space-y-3">
          {[0, 1, 2, 3].map((i) => (
            <div
              key={i}
              className="h-16 animate-pulse rounded-2xl bg-muted"
              style={{ animationDelay: `${i * 120}ms` }}
            />
          ))}
        </div>
      </main>
    )
  }

  if (draft.status === 'OUTLINE_FAILED') {
    return (
      <main className="mx-auto flex max-w-6xl flex-col items-center justify-center px-4 pb-16 pt-32 text-center sm:px-6 lg:px-8">
        <h1 className="text-xl font-semibold">Outline generation failed</h1>
        <p className="mt-2 max-w-md text-sm text-muted-foreground">
          {outlineError ?? 'Something went wrong while generating your outline.'}
        </p>
        <div className="mt-6 flex gap-3">
          <Button onClick={handleRegenerate} disabled={isRegenerating}>
            {isRegenerating ? 'Retrying…' : 'Try again'}
          </Button>
          <Button variant="outline" onClick={() => navigate({ to: '/home' })}>
            Back to home
          </Button>
        </div>
      </main>
    )
  }

  return (
    <main className="mx-auto max-w-6xl space-y-5 px-4 pb-16 pt-24 sm:px-6 lg:px-8">
      <OutlineToolbar
        title={draft.title}
        updatedAt={draft.updatedAt}
        isRegenerating={isRegenerating}
        isGeneratingPresentation={isGeneratingPresentation}
        onRegenerate={handleRegenerate}
        onAddSlide={handleAddSlide}
        onGeneratePresentation={handleGeneratePresentation}
      />

      <p className="text-sm text-muted-foreground">{slideCountLabel}</p>

      <OutlineSlideList
        slides={draft.slides}
        savingSlideId={savingSlideId}
        onSlideChange={handleSlideChange}
        onDeleteSlide={handleDeleteSlide}
        onReorder={handleReorder}
      />
    </main>
  )
}
